pipeline:
  name: "Demo_KT "
  identifier: Demo_KT
  projectIdentifier: demoKt
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: KT_session
        build: <+input>
  stages:
    - stage:
        name: ci
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo hello
